server:
  port: 8765

spring:
  application:
    name: springboot-jwt-service
  redis:
    # Redis数据库索引（默认为0）
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    # 连接超时时间（毫秒）
    timeout: 1000
    jedis:
      pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 10
      # 连接池中的最小空闲连接
      min-idle: 0



eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/  # 注册中心

battcn:
  security:
    token:
      expiration-time: 10 # 分钟 1440
      refresh-exp-time: 30 # 分钟 2880
      issuer: AUTHJWT
      signing-key: battcn


