server:
  port: 8764

spring:
  application:
    name: springboot-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #为true表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务
          enabled: false
          #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了
          lower-case-service-id: true
      routes:
        - id: springboot-eureka-client-demo
          uri: lb://SPRINGBOOT-EUREKA-CLIENT-DEMO
          predicates:
            - Path=/test/**
          filters:
            #用StripPrefix的filter 在转发之前将/demo去掉
            - StripPrefix=1
        - id: springboot-service-fegin-service
          uri: lb://SPRINGBOOT-SERVICE-FEGIN-SERVICE
          predicates:
            - Path=/game/**
          filters:
            #用StripPrefix的filter 在转发之前将/demo去掉
            - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/


