server:
  port: 7002

spring:
  dubbo:
    application:
      name: springboot-dubbo-provider
    registry:
      address: zookeeper://192.168.20.224:2181
    protocol:
      name: dubbo
      port: 20880
    scan: com.example.provider.serviceimpl

