server:
  port: 8886

spring:
  application:
    name: springcloud-nacos-discovery-server1
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.224:8848
        namespace: 216011c0-eac8-473c-a889-0a30874e4822



useLocalCache: true